### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by ICEWOLFL** [Nick2bad4u/BHBot#191]
Traceback (most recent call last):
  File "gui.pyw", line 381, in <module>
  File "gui.pyw", line 134, in __init__
  File "gui.pyw", line 237, in create_window
  File "utils.py", line 236, in update_window
  File "utils.py", line 193, in language
  File "utils.py", line 189, in get_language
StopIteration

**Comment by ICEWOLFL** [comment]
Even source code not working 

C:\Users\ICE WOLF\Desktop\BHBot>gui.py
Traceback (most recent call last):
  File "C:\Users\ICE WOLF\Desktop\BHBot\gui.py", line 4, in <module>
    from bot import (
  File "C:\Users\ICE WOLF\Desktop\BHBot\bot.py", line 4, in <module>
    from config import (
  File "C:\Users\ICE WOLF\Desktop\BHBot\config.py", line 3, in <module>
    from abstract_mode import Mode
  File "C:\Users\ICE WOLF\Desktop\BHBot\abstract_mode.py", line 2, in <module>
    from utils import (
  File "C:\Users\ICE WOLF\Desktop\BHBot\utils.py", line 11, in <module>
    import PySimpleGUI as Sg
ModuleNotFoundError: No module named 'PySimpleGUI'

**Comment by Nick2bad4u** [comment]
You need to install the dependencies.

You're missing PySimpleGUI.

go to Python and type "pip install -r requirements.txt" while in the source code folder.

**Comment by ICEWOLFL** [comment]
Didn't worked 

C:\Users\ICE WOLF\Desktop\BHBot>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting altgraph==0.17.4 (from -r requirements.txt (line 1))
  Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting appdirs==1.4.4 (from -r requirements.txt (line 2))
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens==2.4.1 (from -r requirements.txt (line 3))
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 4))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting auto-py-to-exe==2.44.1 (from -r requirements.txt (line 5))
  Using cached auto_py_to_exe-2.44.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting backcall==0.2.0 (from -r requirements.txt (line 6))
  Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 7))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach==6.1.0 (from -r requirements.txt (line 8))
  Using cached bleach-6.1.0-py3-none-any.whl.metadata (30 kB)
Collecting bottle==0.12.25 (from -r requirements.txt (line 9))
  Using cached bottle-0.12.25-py3-none-any.whl.metadata (1.8 kB)
Collecting bottle-websocket==0.2.9 (from -r requirements.txt (line 10))
  Using cached bottle-websocket-0.2.9.tar.gz (2.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bsdiff4==1.2.4 (from -r requirements.txt (line 11))
  Using cached bsdiff4-1.2.4-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
Collecting certifi==2024.7.4 (from -r requirements.txt (line 12))
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting cffi==1.16.0 (from -r requirements.txt (line 13))
  Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting chardet==5.2.0 (from -r requirements.txt (line 14))
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 15))
  Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 16))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting decorator==5.1.1 (from -r requirements.txt (line 17))
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting defusedxml==0.7.1 (from -r requirements.txt (line 18))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting Deprecated==1.2.14 (from -r requirements.txt (line 19))
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting docopt==0.6.2 (from -r requirements.txt (line 20))
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dsdev-utils==1.3.0 (from -r requirements.txt (line 21))
  Using cached dsdev-utils-1.3.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-cue25675\dsdev-utils_495f73f403814c6b8167d7f5dfffc6ef\versioneer.py:500: SyntaxWarning: invalid escape sequence '\s'
        ] = '''
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-h37clia2\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-h37clia2\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-h37clia2\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-h37clia2\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 31, in <module>
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-cue25675\dsdev-utils_495f73f403814c6b8167d7f5dfffc6ef\versioneer.py", line 1518, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-cue25675\dsdev-utils_495f73f403814c6b8167d7f5dfffc6ef\versioneer.py", line 1446, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-cue25675\dsdev-utils_495f73f403814c6b8167d7f5dfffc6ef\versioneer.py", line 416, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Users\ICE WOLF\Desktop\BHBot>

**Comment by ICEWOLFL** [comment]
I have problem with dsdev utilis it's not let me install it help

**Comment by Nick2bad4u** [comment]
> I have problem with dsdev utils it's not let me install it helps

Are you on a Mac?

**Comment by ICEWOLFL** [comment]
I'm from windows I chnage it to 70.0.0 and still same result

**Comment by ICEWOLFL** [comment]
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-k2my8wx_\dsdev-utils_fd094259fcf14610b5d70f8e820efd7d\versioneer.py:500: SyntaxWarning: invalid escape sequence '\s'
        ] = '''
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-vzf9d7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-vzf9d7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-vzf9d7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-build-env-vzf9d7yh\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 31, in <module>
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-k2my8wx_\dsdev-utils_fd094259fcf14610b5d70f8e820efd7d\versioneer.py", line 1518, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-k2my8wx_\dsdev-utils_fd094259fcf14610b5d70f8e820efd7d\versioneer.py", line 1446, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ICE WOLF\AppData\Local\Temp\pip-install-k2my8wx_\dsdev-utils_fd094259fcf14610b5d70f8e820efd7d\versioneer.py", line 416, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Users\ICE WOLF\Desktop\BHBot-bhbot-imugi>

**Comment by ICEWOLFL** [comment]
I opened new user and tried to do it there it worked but I needed to copy the requirements file to python folder and so there the build

**Comment by Nick2bad4u** [comment]
> I opened new user and tried to do it there it worked but I needed to copy the requirements file to python folder and so there the build

You got it working? What do you mean by "new user"

**Comment by ICEWOLFL** [comment]
New windows user and it's working now I just copied the requirements file to python folder and did the the installation and then it's got open working

**Comment by Nick2bad4u** [comment]
> New windows user and it's working now I just copied the requirements file to python folder and did the the installation and then it's got open working

Maybe it was a permissions issue. strange.
