### ISSUE TITLE
"Getting requirements to build wheel did not run successfully."

### ISSUE THREAD

**Issue by krazziu** [Nick2bad4u/BHBot#219]
Having trouble installing the requirements, any ideas?

PS C:\Users\there\Downloads\BHBot-source-code\BHBot> pip install -r requirements.txt
Collecting altgraph==0.17.4 (from -r requirements.txt (line 1))
  Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting appdirs==1.4.4 (from -r requirements.txt (line 2))
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens==2.4.1 (from -r requirements.txt (line 3))
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 4))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting auto-py-to-exe==2.44.1 (from -r requirements.txt (line 5))
  Using cached auto_py_to_exe-2.44.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting backcall==0.2.0 (from -r requirements.txt (line 6))
  Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 7))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach==6.1.0 (from -r requirements.txt (line 8))
  Using cached bleach-6.1.0-py3-none-any.whl.metadata (30 kB)
Collecting bottle==0.12.25 (from -r requirements.txt (line 9))
  Using cached bottle-0.12.25-py3-none-any.whl.metadata (1.8 kB)
Collecting bottle-websocket==0.2.9 (from -r requirements.txt (line 10))
  Using cached bottle-websocket-0.2.9.tar.gz (2.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bsdiff4==1.2.4 (from -r requirements.txt (line 11))
  Using cached bsdiff4-1.2.4-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: certifi==2024.7.4 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (2024.7.4)
Requirement already satisfied: cffi==1.16.0 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 13)) (1.16.0)
Collecting chardet==5.2.0 (from -r requirements.txt (line 14))
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: charset-normalizer==3.3.2 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (3.3.2)
Requirement already satisfied: colorama==0.4.6 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (0.4.6)
Collecting decorator==5.1.1 (from -r requirements.txt (line 17))
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting defusedxml==0.7.1 (from -r requirements.txt (line 18))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting Deprecated==1.2.14 (from -r requirements.txt (line 19))
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting docopt==0.6.2 (from -r requirements.txt (line 20))
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dsdev-utils==1.3.0 (from -r requirements.txt (line 21))
  Using cached dsdev-utils-1.3.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py:500: SyntaxWarning: invalid escape sequence '\s'
        ] = '''
      Traceback (most recent call last):
        File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 31, in <module>
        File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1518, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1446, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 416, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Nick2bad4u** [comment]
> > Having trouble installing the requirements, any ideas?
> > 
> > PS C:\Users\there\Downloads\BHBot-source-code\BHBot> pip install -r requirements.txt Collecting altgraph==0.17.4 (from -r requirements.txt (line 1)) Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB) Collecting appdirs==1.4.4 (from -r requirements.txt (line 2)) Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB) Collecting asttokens==2.4.1 (from -r requirements.txt (line 3)) Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB) Collecting attrs==23.2.0 (from -r requirements.txt (line 4)) Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB) Collecting auto-py-to-exe==2.44.1 (from -r requirements.txt (line 5)) Using cached auto_py_to_exe-2.44.1-py2.py3-none-any.whl.metadata (16 kB) Collecting backcall==0.2.0 (from -r requirements.txt (line 6)) Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB) Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 7)) Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB) Collecting bleach==6.1.0 (from -r requirements.txt (line 8)) Using cached bleach-6.1.0-py3-none-any.whl.metadata (30 kB) Collecting bottle==0.12.25 (from -r requirements.txt (line 9)) Using cached bottle-0.12.25-py3-none-any.whl.metadata (1.8 kB) Collecting bottle-websocket==0.2.9 (from -r requirements.txt (line 10)) Using cached bottle-websocket-0.2.9.tar.gz (2.0 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting bsdiff4==1.2.4 (from -r requirements.txt (line 11)) Using cached bsdiff4-1.2.4-cp312-cp312-win_amd64.whl.metadata (2.7 kB) Requirement already satisfied: certifi==2024.7.4 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (2024.7.4) Requirement already satisfied: cffi==1.16.0 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 13)) (1.16.0) Collecting chardet==5.2.0 (from -r requirements.txt (line 14)) Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB) Requirement already satisfied: charset-normalizer==3.3.2 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (3.3.2) Requirement already satisfied: colorama==0.4.6 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (0.4.6) Collecting decorator==5.1.1 (from -r requirements.txt (line 17)) Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB) Collecting defusedxml==0.7.1 (from -r requirements.txt (line 18)) Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB) Collecting Deprecated==1.2.14 (from -r requirements.txt (line 19)) Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB) Collecting docopt==0.6.2 (from -r requirements.txt (line 20)) Using cached docopt-0.6.2.tar.gz (25 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting dsdev-utils==1.3.0 (from -r requirements.txt (line 21)) Using cached dsdev-utils-1.3.0.tar.gz (25 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> > 
> > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [31 lines of output] C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py:500: SyntaxWarning: invalid escape sequence '\s' ] = ''' Traceback (most recent call last): File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=[]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires self.run_setup() File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup super().run_setup(setup_script=setup_script) File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup exec(code, locals()) File "", line 31, in File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1518, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1446, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 416, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output]
> > 
> > note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> > 
> > × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> > 
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> 

What version of python are you using? If you're using 3.12 or higher, try switching to Python 3.11.9.
[**@krazziu**](https://github.com/krazziu) commented on [Oct 4, 2024, 11:19 PM EDT](https://github.com/Nick2bad4u/BHBot/issues/219#issue-2567620927 "2024-10-05T03:19:07Z - Replied by Github Reply Comments"):
> Having trouble installing the requirements, any ideas?
> 
> PS C:\Users\there\Downloads\BHBot-source-code\BHBot> pip install -r requirements.txt
> Collecting altgraph==0.17.4 (from -r requirements.txt (line 1))
>   Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
> Collecting appdirs==1.4.4 (from -r requirements.txt (line 2))
>   Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
> Collecting asttokens==2.4.1 (from -r requirements.txt (line 3))
>   Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
> Collecting attrs==23.2.0 (from -r requirements.txt (line 4))
>   Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
> Collecting auto-py-to-exe==2.44.1 (from -r requirements.txt (line 5))
>   Using cached auto_py_to_exe-2.44.1-py2.py3-none-any.whl.metadata (16 kB)
> Collecting backcall==0.2.0 (from -r requirements.txt (line 6))
>   Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB)
> Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 7))
>   Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
> Collecting bleach==6.1.0 (from -r requirements.txt (line 8))
>   Using cached bleach-6.1.0-py3-none-any.whl.metadata (30 kB)
> Collecting bottle==0.12.25 (from -r requirements.txt (line 9))
>   Using cached bottle-0.12.25-py3-none-any.whl.metadata (1.8 kB)
> Collecting bottle-websocket==0.2.9 (from -r requirements.txt (line 10))
>   Using cached bottle-websocket-0.2.9.tar.gz (2.0 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting bsdiff4==1.2.4 (from -r requirements.txt (line 11))
>   Using cached bsdiff4-1.2.4-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
> Requirement already satisfied: certifi==2024.7.4 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (2024.7.4)
> Requirement already satisfied: cffi==1.16.0 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 13)) (1.16.0)
> Collecting chardet==5.2.0 (from -r requirements.txt (line 14))
>   Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
> Requirement already satisfied: charset-normalizer==3.3.2 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (3.3.2)
> Requirement already satisfied: colorama==0.4.6 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (0.4.6)
> Collecting decorator==5.1.1 (from -r requirements.txt (line 17))
>   Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
> Collecting defusedxml==0.7.1 (from -r requirements.txt (line 18))
>   Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
> Collecting Deprecated==1.2.14 (from -r requirements.txt (line 19))
>   Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
> Collecting docopt==0.6.2 (from -r requirements.txt (line 20))
>   Using cached docopt-0.6.2.tar.gz (25 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting dsdev-utils==1.3.0 (from -r requirements.txt (line 21))
>   Using cached dsdev-utils-1.3.0.tar.gz (25 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [31 lines of output]
>       C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py:500: SyntaxWarning: invalid escape sequence '\s'
>         ] = '''
>       Traceback (most recent call last):
>         File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
>           exec(code, locals())
>         File "<string>", line 31, in <module>
>         File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1518, in get_version
>           return get_versions()["version"]
>                  ^^^^^^^^^^^^^^
>         File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1446, in get_versions
>           cfg = get_config_from_root(root)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 416, in get_config_from_root
>           parser = configparser.SafeConfigParser()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>       AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

If you're using python 3.12 or above, trying installing and running it with 3.11.9.

**Comment by Nick2bad4u** [comment]
> Having trouble installing the requirements, any ideas?
> 
> PS C:\Users\there\Downloads\BHBot-source-code\BHBot> pip install -r requirements.txt Collecting altgraph==0.17.4 (from -r requirements.txt (line 1)) Using cached altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB) Collecting appdirs==1.4.4 (from -r requirements.txt (line 2)) Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB) Collecting asttokens==2.4.1 (from -r requirements.txt (line 3)) Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB) Collecting attrs==23.2.0 (from -r requirements.txt (line 4)) Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB) Collecting auto-py-to-exe==2.44.1 (from -r requirements.txt (line 5)) Using cached auto_py_to_exe-2.44.1-py2.py3-none-any.whl.metadata (16 kB) Collecting backcall==0.2.0 (from -r requirements.txt (line 6)) Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB) Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 7)) Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB) Collecting bleach==6.1.0 (from -r requirements.txt (line 8)) Using cached bleach-6.1.0-py3-none-any.whl.metadata (30 kB) Collecting bottle==0.12.25 (from -r requirements.txt (line 9)) Using cached bottle-0.12.25-py3-none-any.whl.metadata (1.8 kB) Collecting bottle-websocket==0.2.9 (from -r requirements.txt (line 10)) Using cached bottle-websocket-0.2.9.tar.gz (2.0 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting bsdiff4==1.2.4 (from -r requirements.txt (line 11)) Using cached bsdiff4-1.2.4-cp312-cp312-win_amd64.whl.metadata (2.7 kB) Requirement already satisfied: certifi==2024.7.4 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (2024.7.4) Requirement already satisfied: cffi==1.16.0 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 13)) (1.16.0) Collecting chardet==5.2.0 (from -r requirements.txt (line 14)) Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB) Requirement already satisfied: charset-normalizer==3.3.2 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (3.3.2) Requirement already satisfied: colorama==0.4.6 in c:\users\there\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (0.4.6) Collecting decorator==5.1.1 (from -r requirements.txt (line 17)) Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB) Collecting defusedxml==0.7.1 (from -r requirements.txt (line 18)) Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB) Collecting Deprecated==1.2.14 (from -r requirements.txt (line 19)) Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB) Collecting docopt==0.6.2 (from -r requirements.txt (line 20)) Using cached docopt-0.6.2.tar.gz (25 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting dsdev-utils==1.3.0 (from -r requirements.txt (line 21)) Using cached dsdev-utils-1.3.0.tar.gz (25 kB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [31 lines of output] C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py:500: SyntaxWarning: invalid escape sequence '\s' ] = ''' Traceback (most recent call last): File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=[]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires self.run_setup() File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup super().run_setup(setup_script=setup_script) File "C:\Users\there\AppData\Local\Temp\pip-build-env-pr3496ly\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup exec(code, locals()) File "", line 31, in File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1518, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 1446, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\there\AppData\Local\Temp\pip-install-rtbpzmos\dsdev-utils_98fc41064048492ba65b66118e83cfa4\versioneer.py", line 416, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

If you're using version 3.12 of python, try using 3.11.9.
