### ISSUE TITLE
I have Issue to run

### ISSUE THREAD

**Issue by Poo0oof** [Nick2bad4u/BHBot#248]
2024-11-05 02:41:35,095 DEBUG Loading installation info
Expecting value: line 1 column 1 (char 0)
NoneType: None
Expecting value: line 1 column 1 (char 0)
NoneType: None
Traceback (most recent call last):
2024-11-05 02:41:35,608 DEBUG Loading installation info
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\gui.py", line 4, in <module>
2024-11-05 02:41:35,608 DEBUG Loading installation info
    from bot import (
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\bot.py", line 4, in <module>
    from config import (
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\config.py", line 3, in <module>
    from abstract_mode import Mode
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\abstract_mode.py", line 2, in <module>
    from utils import (
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\utils.py", line 355, in <module>
    global_settings = Settings.load()
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\utils.py", line 170, in load
    return cls({})
  File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\utils.py", line 123, in __init__
    pyupdater_client = Client(
  File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\site-packages\pyupdater\client\__init__.py", line 213, in __init__
    self.refresh()
  File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\site-packages\pyupdater\client\__init__.py", line 217, in refresh
    self._get_signing_key()
  File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\site-packages\pyupdater\client\__init__.py", line 368, in _get_signing_key
    key_data = json.loads(key_data_str.decode("utf-8"))
  File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Nick2bad4u** [comment]
> 2024-11-05 02:41:35,095 DEBUG Loading installation info Expecting value: line 1 column 1 (char 0) NoneType: None Expecting value: line 1 column 1 (char 0) NoneType: None Traceback (most recent call last): 2024-11-05 02:41:35,608 DEBUG Loading installation info File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\gui.py", line 4, in 2024-11-05 02:41:35,608 DEBUG Loading installation info from bot import ( File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\bot.py", line 4, in from config import ( File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\config.py", line 3, in from abstract_mode import Mode File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\abstract_mode.py", line 2, in from utils import ( File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\utils.py", line 355, in global_settings = Settings.load() File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\utils.py", line 170, in load return cls({}) File "C:\Users\moham\OneDrive\Desktop\CodeName\BHBot-main\utils.py", line 123, in **init** pyupdater_client = Client( File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\site-packages\pyupdater\client__init__.py", line 213, in **init** self.refresh() File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\site-packages\pyupdater\client__init__.py", line 217, in refresh self._get_signing_key() File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\site-packages\pyupdater\client__init__.py", line 368, in _get_signing_key key_data = json.loads(key_data_str.decode("utf-8")) File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Users\moham\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

bots broken due to new UI update, and I dont have time to fix it atm
